- name: allow connections on configured ports
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    source: "{{ item.source }}"
  with_items: "{{ iptables.accept }}"
  notify:
    - persist iptables

- name: allow established connections
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT
  notify:
    - persist iptables

- name: allow loopback input
  iptables: chain=INPUT in_interface=lo jump=ACCEPT
  notify:
    - persist iptables

- name: allow loopback output
  iptables: chain=OUTPUT out_interface=lo jump=ACCEPT
  notify:
    - persist iptables

- name: drop all other connections
  command: iptables -P INPUT DROP
  notify:
    - persist iptables

